### ISSUE TITLE
Missing Contacts list

### ISSUE THREAD

**Issue by nowave7** [qtinsider/meegram2#1]
There is no list of contacts, and no way to start a new chat, unless a chat has already been started on other device.
When tapping on plus button on the home screen, a popup appears with a "Create" line with cross to the right, and selecting any of the two, just closes the popup.
![2021-06-06_15-28-39](https://user-images.githubusercontent.com/1130101/120926092-cdee0e00-c6db-11eb-9ec1-e1ef6b15aff1.png)

**Comment by qtinsider** [comment]
OK,  on next release
