### ISSUE TITLE
After changing the system language to certain languages, the software will not work properly

### ISSUE THREAD

**Issue by EX3124** [qtinsider/meegram2#8]
After Connecting, the app should jump to the contacts view, but it doesn't do that, it just keeps loading, like this
![20140916045751](https://github.com/user-attachments/assets/f893e39d-2eb7-44ef-81d5-92d9f36e60c3)

As shown in the figure, these languages ​​can trigger this problem
![20140916045453](https://github.com/user-attachments/assets/6f0c8277-09a0-4117-8eb5-9ea4b0beed44)

**Comment by qtinsider** [comment]
**Thanks for reporting this issue!**

Unfortunately, I don’t have the device to test this issue directly at the moment, but I’ll definitely look into fixing it after the next release. I appreciate your patience!
